# Generated by Django 4.0.3 on 2022-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-3-4'),
            preserve_default=False,
        ),
    ]
